import { DataSource } from "typeorm";
import { Quote } from "../../quotes/entities/quote.entity";
import AppDataSource from "../../../ormconfig";

async function seed() {
  try {
    console.log("Connecting to database...");
    await AppDataSource.initialize();
    console.log("Connected.");

    const quoteRepository = AppDataSource.getRepository(Quote);

    console.log("Clearing quotes table...");
    await quoteRepository.clear();

    console.log("Seeding quotes...");
    const quotes = [
      { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', tags: 'work;inspiration', likes: 0 },
      { text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon', tags: 'life;wisdom', likes: 0 },
      { text: 'Get busy living or get busy dying.', author: 'Stephen King', tags: 'life;motivation', likes: 0 },
      { text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West', tags: 'life;humor', likes: 0 },
      { text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas A. Edison', tags: 'failure;success;perseverance', likes: 0 },
      { text: 'If you want to live a happy life, tie it to a goal, not to people or things.', author: 'Albert Einstein', tags: 'happiness;goals', likes: 0 },
      { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth', tags: 'sports;courage', likes: 0 },
      { text: 'Money and success don’t change people; they merely amplify what is already there.', author: 'Will Smith', tags: 'money;success;character', likes: 0 },
      { text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs', tags: 'time;life;individuality', likes: 0 },
      { text: 'Not how long, but how well you have lived is the main thing.', author: 'Seneca', tags: 'life;wisdom;stoicism', likes: 0 },
      { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', tags: 'motivation;persistence', likes: 0 },
      { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', tags: 'motivation;fear', likes: 0 },
      { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', tags: 'success;failure;courage', likes: 0 },
      { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis', tags: 'motivation;destiny', likes: 0 },
      { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', tags: 'motivation;belief', likes: 0 },
      { text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt', tags: 'motivation;future', likes: 0 },
      { text: 'Creativity is intelligence having fun.', author: 'Albert Einstein', tags: 'creativity;motivation', likes: 0 },
      { text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar', tags: 'motivation;growth', likes: 0 },
      { text: 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', author: 'Thomas A. Edison', tags: 'persistence;failure', likes: 0 },
      { text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson', tags: 'persistence;action', likes: 0 },
      { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', tags: 'dreams;future', likes: 0 },
      { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe', tags: 'motivation;action', likes: 0 },
      { text: 'Fall seven times and stand up eight.', author: 'Japanese Proverb', tags: 'persistence;resilience', likes: 0 },
      { text: 'Everything has beauty, but not everyone can see.', author: 'Confucius', tags: 'beauty;perspective', likes: 0 },
      { text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank', tags: 'inspiration;action', likes: 0 },
      { text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt', tags: 'persistence;hope', likes: 0 },
      { text: 'It is never too late to be what you might have been.', author: 'George Eliot', tags: 'motivation;potential', likes: 0 },
      { text: 'Winning isn\'t everything, but wanting to win is.', author: 'Vince Lombardi', tags: 'winning;motivation', likes: 0 },
      { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey', tags: 'responsibility;choices', likes: 0 },
      { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain', tags: 'motivation;action', likes: 0 },
      { text: 'Goal setting is the secret to a compelling future.', author: 'Tony Robbins', tags: 'goals;future', likes: 0 },
      { text: 'If you can dream it, you can do it.', author: 'Walt Disney', tags: 'dreams;inspiration', likes: 0 },
      { text: 'Aim for the moon. If you miss, you may hit a star.', author: 'W. Clement Stone', tags: 'ambition;goals', likes: 0 },
      { text: 'A winner is a dreamer who never gives up.', author: 'Nelson Mandela', tags: 'winning;persistence', likes: 0 },
      { text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'Unknown', tags: 'persistence;hard-work', likes: 0 },
      { text: 'Opportunities don\'t happen, you create them.', author: 'Chris Grosser', tags: 'opportunity;success', likes: 0 },
      { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', tags: 'success;work', likes: 0 },
      { text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', tags: 'risk;success', likes: 0 },
      { text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson', tags: 'luck;work', likes: 0 },
      { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill', tags: 'success;attitude', likes: 0 },
      { text: 'If you are not willing to risk the usual, you will have to settle for the ordinary.', author: 'Jim Rohn', tags: 'risk;success', likes: 0 },
      { text: 'Stop chasing the money and start chasing the passion.', author: 'Tony Hsieh', tags: 'passion;success', likes: 0 },
      { text: 'All our dreams can come true if we have the courage to pursue them.', author: 'Walt Disney', tags: 'dreams;courage', likes: 0 },
      { text: 'If you do what you\'ve always done, you\'ll get what you\'ve always gotten.', author: 'Tony Robbins', tags: 'change;results', likes: 0 },
      { text: 'Dream big and dare to fail.', author: 'Norman Vaughan', tags: 'dreams;courage', likes: 0 },
      { text: 'You may be disappointed if you fail, but you are doomed if you don\'t try.', author: 'Beverly Sills', tags: 'failure;action', likes: 0 },
      { text: 'Life is 10% what happens to me and 90% of how I react to it.', author: 'Charles Swindoll', tags: 'attitude;life', likes: 0 },
      { text: 'To handle yourself, use your head; to handle others, use your heart.', author: 'Eleanor Roosevelt', tags: 'leadership;empathy', likes: 0 },
      { text: 'Whatever the mind of man can conceive and believe, it can achieve.', author: 'Napoleon Hill', tags: 'belief;success', likes: 0 },
      { text: 'Winning is a habit. Unfortunately, so is losing.', author: 'Vince Lombardi', tags: 'winning;habits', likes: 0 },
      { text: 'Winners never quit, and quitters never win.', author: 'Vince Lombardi', tags: 'winning;persistence', likes: 0 },
      { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso', tags: 'action;success', likes: 0 },
      { text: 'Victory is sweetest when you\'ve known defeat.', author: 'Malcolm S. Forbes', tags: 'winning;victory', likes: 0 },
      { text: 'The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.', author: 'Confucius', tags: 'winning;excellence', likes: 0 },
      { text: 'Strength does not come from winning. Your struggles develop your strengths.', author: 'Arnold Schwarzenegger', tags: 'strength;struggle', likes: 0 },
      { text: 'You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.', author: 'Zig Ziglar', tags: 'winning;planning', likes: 0 },
      { text: 'There is no substitute for victory.', author: 'Douglas MacArthur', tags: 'winning;victory', likes: 0 },
      { text: 'Winning takes talent, to repeat takes character.', author: 'John Wooden', tags: 'winning;character', likes: 0 },
      { text: 'Persistence guarantees that results are inevitable.', author: 'Paramahansa Yogananda', tags: 'persistence;results', likes: 0 },
      { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin', tags: 'persistence;energy', likes: 0 },
      { text: 'Patience, persistence and perspiration make an unbeatable combination for success.', author: 'Napoleon Hill', tags: 'success;persistence', likes: 0 },
      { text: 'Ambition is the path to success. Persistence is the vehicle you arrive in.', author: 'Bill Bradley', tags: 'ambition;persistence', likes: 0 },
      { text: 'Paralyze resistance with persistence.', author: 'Woody Hayes', tags: 'persistence;resistance', likes: 0 },
      { text: 'Rivers know this: there is no hurry. We shall get there some day.', author: 'A.A. Milne', tags: 'patience;persistence', likes: 0 },
      { text: 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', author: 'Vince Lombardi', tags: 'willpower;success', likes: 0 },
      { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden', tags: 'focus;ability', likes: 0 },
      { text: 'Failure is the condiment that gives success its flavor.', author: 'Truman Capote', tags: 'failure;success', likes: 0 },
      { text: 'Defeat is not the worst of failures. Not to have tried is the true failure.', author: 'George Edward Woodberry', tags: 'failure;trying', likes: 0 },
      { text: 'There is no failure except in no longer trying.', author: 'Elbert Hubbard', tags: 'failure;persistence', likes: 0 },
      { text: 'A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.', author: 'Elbert Hubbard', tags: 'persistence;hope', likes: 0 },
      { text: 'Life is beautiful.', author: 'Roberto Benigni', tags: 'life;beauty', likes: 0 },
      { text: 'Life is a flower of which love is the honey.', author: 'Victor Hugo', tags: 'life;love', likes: 0 },
      { text: 'Keep your face always toward the sunshine—and shadows will fall behind you.', author: 'Walt Whitman', tags: 'optimism;life', likes: 0 },
      { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius', tags: 'life;simplicity', likes: 0 },
      { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost', tags: 'life;resilience', likes: 0 },
      { text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller', tags: 'life;adventure', likes: 0 },
      { text: 'Good friends, good books, and a sleepy conscience: this is the ideal life.', author: 'Mark Twain', tags: 'life;friends', likes: 0 },
      { text: 'Life is short, and it is up to you to make it sweet.', author: 'Sarah Louise Delany', tags: 'life;happiness', likes: 0 },
      { text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama', tags: 'life;happiness', likes: 0 },
      { text: 'Life is a long lesson in humility.', author: 'James M. Barrie', tags: 'life;humility', likes: 0 },
      { text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', author: 'Buddha', tags: 'life;mindfulness', likes: 0 },
      { text: 'Life is not a problem to be solved, but a reality to be experienced.', author: 'Søren Kierkegaard', tags: 'life;experience', likes: 0 },
      { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey', tags: 'life;wisdom', likes: 0 },
      { text: 'The biggest adventure you can take is to live the life of your dreams.', author: 'Oprah Winfrey', tags: 'life;dreams', likes: 0 },
      { text: 'Life shrinks or expands in proportion to one\'s courage.', author: 'Anaïs Nin', tags: 'life;courage', likes: 0 },
      { text: 'Live in the sunshine, swim the sea, drink the wild air.', author: 'Ralph Waldo Emerson', tags: 'life;nature', likes: 0 },
      { text: 'Life is trying things to see if they work.', author: 'Ray Bradbury', tags: 'life;experimentation', likes: 0 },
      { text: 'Life isn\'t about finding yourself. Life is about creating yourself.', author: 'George Bernard Shaw', tags: 'life;creation', likes: 0 },
      { text: 'Life is too important to be taken seriously.', author: 'Oscar Wilde', tags: 'life;humor', likes: 0 },
      { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde', tags: 'life;living', likes: 0 },
      { text: 'Life is 10 percent what you make it, and 90 percent how you take it.', author: 'Irving Berlin', tags: 'life;attitude', likes: 0 },
      { text: 'Love the life you live. Live the life you love.', author: 'Bob Marley', tags: 'life;love', likes: 0 },
      { text: 'Life is better when you are laughing.', author: 'Unknown', tags: 'life;happiness', likes: 0 },
      { text: 'Enjoy the little things, for one day you may look back and realize they were the big things.', author: 'Robert Brault', tags: 'life;gratitude', likes: 0 },
      { text: 'Life is a journey that must be traveled no matter how bad the roads and accommodations.', author: 'Oliver Goldsmith', tags: 'life;journey', likes: 0 },
      { text: 'The good life is one inspired by love and guided by knowledge.', author: 'Bertrand Russell', tags: 'life;love;knowledge', likes: 0 },
      { text: 'Life is a succession of lessons which must be lived to be understood.', author: 'Ralph Waldo Emerson', tags: 'life;lessons', likes: 0 },
      { text: 'My life is my message.', author: 'Mahatma Gandhi', tags: 'life;integrity', likes: 0 },
      { text: 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', author: 'Maya Angelou', tags: 'life;moments', likes: 0 },
      { text: 'Life is the art of drawing without an eraser.', author: 'John W. Gardner', tags: 'life;art', likes: 0 },
      { text: 'Life is short, break the rules, forgive quickly, kiss slowly, love truly, laugh uncontrollably, and never regret anything that made you smile.', author: 'Mark Twain', tags: 'life;joy', likes: 0 },
      { text: 'The most important thing is to enjoy your life—to be happy—it\'s all that matters.', author: 'Audrey Hepburn', tags: 'life;happiness', likes: 0 },
      { text: 'Life is what we make it, always has been, always will be.', author: 'Grandma Moses', tags: 'life;responsibility', likes: 0 },
      { text: 'Life is like riding a bicycle. To keep your balance, you must keep moving.', author: 'Albert Einstein', tags: 'life;balance', likes: 0 },
      { text: 'Life is a question and how we live it is our answer.', author: 'Gary Keller', tags: 'life;purpose', likes: 0 },
      { text: 'Every moment is a fresh beginning.', author: 'T.S. Eliot', tags: 'life;hope', likes: 0 },
      { text: 'Lighten up, just enjoy life, smile more, laugh more, and don\'t get so worked up about things.', author: 'Kenneth Branagh', tags: 'life;joy', likes: 0 },
      { text: 'Because of your smile, you make life more beautiful.', author: 'Thich Nhat Hanh', tags: 'life;smile', likes: 0 },
      { text: 'Life is beautiful because it doesn\'t last.', author: 'Brit Marling', tags: 'life;impermanence', likes: 0 },
      { text: 'The beauty of life is, while we cannot undo what is done, we can see it, understand it, learn from it and change.', author: 'Jennifer Edwards', tags: 'life;learning', likes: 0 },
      { text: 'Life is a beautiful struggle.', author: 'Talib Kweli', tags: 'life;struggle', likes: 0 },
      { text: 'Life is beautiful if you know where to look.', author: 'Unknown', tags: 'life;perspective', likes: 0 },
      { text: 'There is beauty in everything, just not everybody sees it.', author: 'Andy Warhol', tags: 'beauty;perception', likes: 0 },
      { text: 'Life is full of beauty. Notice it.', author: 'Ashley Smith', tags: 'life;beauty', likes: 0 },
      { text: 'Beauty is power; a smile is its sword.', author: 'John Ray', tags: 'beauty;smile', likes: 0 },
      { text: 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.', author: 'Marcus Aurelius', tags: 'life;stars', likes: 0 },
      { text: 'Life is beautiful not because of the things we see or do. Life is beautiful because of the people we meet.', author: 'Simon Sinek', tags: 'life;people', likes: 0 },
      { text: 'Find ecstasy in life; the mere sense of living is joy enough.', author: 'Emily Dickinson', tags: 'life;joy', likes: 0 },
      { text: 'Life is a one time offer, use it well.', author: 'Unknown', tags: 'life;opportunity', likes: 0 },
      { text: 'Simply enjoy life and the great pleasures that come with it.', author: 'Karolina Kurkova', tags: 'life;pleasure', likes: 0 },
      { text: 'Life is short, and truth works far and lives long: let us speak the truth.', author: 'Arthur Schopenhauer', tags: 'life;truth', likes: 0 },
      { text: 'The trick in life is learning how to deal with it.', author: 'Helen Mirren', tags: 'life;resilience', likes: 0 },
      { text: 'Life is a daring adventure or nothing.', author: 'Helen Keller', tags: 'life;adventure', likes: 0 },
      { text: 'Only a life lived for others is a life worthwhile.', author: 'Albert Einstein', tags: 'life;service', likes: 0 },
      { text: 'Life is what you make it.', author: 'Eleanor Roosevelt', tags: 'life;attitude', likes: 0 },
      { text: 'The best things in life are free.', author: 'Unknown', tags: 'life;simplicity', likes: 0 },
      { text: 'Life is beautiful, enjoy the ride.', author: 'Unknown', tags: 'life;journey', likes: 0 },
      { text: 'Beautiful things happen when you distance yourself from negativity.', author: 'Unknown', tags: 'life;positivity', likes: 0 },
      { text: 'Life is amazing. And then it\'s awful. And then it\'s amazing again.', author: 'L.R. Knost', tags: 'life;ups-downs', likes: 0 },
      { text: 'Live for each second without hesitation.', author: 'Elton John', tags: 'life;carpe-diem', likes: 0 },
      { text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky', tags: 'sports;risk', likes: 0 },
      { text: 'I\'ve missed more than 9000 shots in my career. I\'ve lost almost 300 games. 26 times, I\'ve been trusted to take the game winning shot and missed. I\'ve failed over and over and over again in my life. And that is why I succeed.', author: 'Michael Jordan', tags: 'sports;failure;success', likes: 0 },
      { text: 'Hard work beats talent when talent doesn\'t work hard.', author: 'Tim Notke', tags: 'sports;work', likes: 0 },
      { text: 'It\'s not whether you get knocked down; it\'s whether you get up.', author: 'Vince Lombardi', tags: 'sports;resilience', likes: 0 },
      { text: 'Champions keep playing until they get it right.', author: 'Billie Jean King', tags: 'sports;champions', likes: 0 },
      { text: 'I hated every minute of training, but I said, "Don\'t quit. Suffer now and live the rest of your life as a champion."', author: 'Muhammad Ali', tags: 'sports;discipline', likes: 0 },
      { text: 'The more difficult the victory, the greater the happiness in winning.', author: 'Pele', tags: 'sports;victory', likes: 0 },
      { text: 'If you fail to prepare, you\'re prepared to fail.', author: 'Mark Spitz', tags: 'sports;preparation', likes: 0 },
      { text: 'A trophy carries dust. Memories last forever.', author: 'Mary Lou Retton', tags: 'sports;memories', likes: 0 },
      { text: 'You can\'t put a limit on anything. The more you dream, the farther you get.', author: 'Michael Phelps', tags: 'sports;dreams', likes: 0 },
      { text: 'It is not the size of a man but the size of his heart that matters.', author: 'Evander Holyfield', tags: 'sports;heart', likes: 0 },
      { text: 'Wisdom is always an overmatch for strength.', author: 'Phil Jackson', tags: 'sports;wisdom', likes: 0 },
      { text: 'Talent wins games, but teamwork and intelligence win championships.', author: 'Michael Jordan', tags: 'sports;teamwork', likes: 0 },
      { text: 'I don\'t count my sit-ups; I only start counting when it starts hurting because they\'re the only ones that count.', author: 'Muhammad Ali', tags: 'sports;effort', likes: 0 },
      { text: 'Excellence is not a singular act but a habit. You are what you do repeatedly.', author: 'Shaquille O\'Neal', tags: 'sports;habits', likes: 0 },
      { text: 'Nobody who ever gave his best regretted it.', author: 'George Halas', tags: 'sports;effort', likes: 0 },
      { text: 'Run when you can, walk if you have to, crawl if you must; just never give up.', author: 'Dean Karnazes', tags: 'sports;persistence', likes: 0 },
      { text: 'Today I will do what others won\'t, so tomorrow I can accomplish what others can\'t.', author: 'Jerry Rice', tags: 'sports;discipline', likes: 0 },
      { text: 'The principle is competing against yourself. It\'s about self-improvement, about being better than you were the day before.', author: 'Steve Young', tags: 'sports;improvement', likes: 0 },
      { text: 'Service to others is the rent you pay for your room here on earth.', author: 'Muhammad Ali', tags: 'service;life', likes: 0 },
      { text: 'Age is no barrier. It\'s a limitation you put on your mind.', author: 'Jackie Joyner-Kersee', tags: 'sports;age', likes: 0 },
      { text: 'I always felt that my greatest asset was not my physical ability, it was my mental ability.', author: 'Bruce Jenner', tags: 'sports;mindset', likes: 0 },
      { text: 'There may be people that have more talent than you, but there\'s no excuse for anyone to work harder than you do.', author: 'Derek Jeter', tags: 'sports;work', likes: 0 },
      { text: 'One man practicing sportsmanship is far better than 50 preaching it.', author: 'Knute Rockne', tags: 'sports;character', likes: 0 },
      { text: 'It\'s hard to beat a person who never gives up.', author: 'Babe Ruth', tags: 'sports;persistence', likes: 0 },
      { text: 'Just play. Have fun. Enjoy the game.', author: 'Michael Jordan', tags: 'sports;joy', likes: 0 },
      { text: 'My motto was always to keep swinging. Whether I was in a slump or feeling badly or having trouble off the field, the only thing to do was keep swinging.', author: 'Hank Aaron', tags: 'sports;persistence', likes: 0 },
      { text: 'Show me a guy who\'s afraid to look bad, and I\'ll show you a guy you can beat every time.', author: 'Lou Brock', tags: 'sports;courage', likes: 0 },
      { text: 'Procrastination is one of the most common and deadliest of diseases and its toll on success and happiness is heavy.', author: 'Wayne Gretzky', tags: 'sports;discipline', likes: 0 },
      { text: 'You control your own wins and losses.', author: 'Maria Sharapova', tags: 'sports;responsibility', likes: 0 },
      { text: 'I think that everything is possible as long as you put your mind to it and you put the work and time into it.', author: 'Michael Phelps', tags: 'sports;possibility', likes: 0 },
      { text: 'Winning isn\'t getting ahead of others. It is getting ahead of yourself.', author: 'Roger Staubach', tags: 'sports;improvement', likes: 0 },
      { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden', tags: 'sports;focus', likes: 0 },
      { text: 'Success is where preparation and opportunity meet.', author: 'Bobby Unser', tags: 'sports;success', likes: 0 },
      { text: 'Set your goals high, and don\'t stop till you get there.', author: 'Bo Jackson', tags: 'sports;goals', likes: 0 },
      { text: 'The road to Easy Street goes through the sewer.', author: 'John Madden', tags: 'sports;struggle', likes: 0 },
      { text: 'If you aren\'t going all the way, why go at all?', author: 'Joe Namath', tags: 'sports;commitment', likes: 0 },
      { text: 'You have to expect things of yourself before you can do them.', author: 'Michael Jordan', tags: 'sports;belief', likes: 0 },
      { text: 'Obstacles don\'t have to stop you. If you run into a wall, don\'t turn around and give up. Figure out how to climb it, go through it, or work around it.', author: 'Michael Jordan', tags: 'sports;obstacles', likes: 0 },
      { text: 'Some people want it to happen, some wish it would happen, others make it happen.', author: 'Michael Jordan', tags: 'sports;action', likes: 0 },
      { text: 'I know what I have to do, and I\'m going to do whatever it takes. If I do it, I\'ll come out a winner, and it doesn\'t matter what anyone else does.', author: 'Florence Griffith Joyner', tags: 'sports;determination', likes: 0 },
      { text: 'The difference between the impossible and the possible lies in a man\'s determination.', author: 'Tommy Lasorda', tags: 'sports;determination', likes: 0 },
      { text: 'When you\'ve got something to prove, there\'s nothing greater than a challenge.', author: 'Terry Bradshaw', tags: 'sports;challenge', likes: 0 },
      { text: 'Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside and something else will take its place. If I quit, however, it lasts forever.', author: 'Lance Armstrong', tags: 'sports;pain;persistence', likes: 0 },
      { text: 'Gold medals aren\'t really made of gold. They\'re made of sweat, determination, and a hard-to-find alloy called guts.', author: 'Dan Gable', tags: 'sports;effort', likes: 0 },
      { text: 'Never say never because limits, like fears, are often just an illusion.', author: 'Michael Jordan', tags: 'sports;limits', likes: 0 },
      { text: 'He who is not courageous enough to take risks will accomplish nothing in life.', author: 'Muhammad Ali', tags: 'sports;risk', likes: 0 },
      { text: 'Impossible is just a big word thrown around by small men who find it easier to live in the world they\'ve been given than to explore the power they have to change it.', author: 'Muhammad Ali', tags: 'sports;impossible', likes: 0 },
      { text: 'Don\'t count the days, make the days count.', author: 'Muhammad Ali', tags: 'sports;time', likes: 0 },
      { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali', tags: 'sports;style', likes: 0 },
      { text: 'A champion is someone who gets up when he can\'t.', author: 'Jack Dempsey', tags: 'sports;resilience', likes: 0 },
      { text: 'The fight is won or lost far away from witnesses - behind the lines, in the gym, and out there on the road, long before I dance under those lights.', author: 'Muhammad Ali', tags: 'sports;preparation', likes: 0 },
      { text: 'If you can\'t accept losing, you can\'t win.', author: 'Vince Lombardi', tags: 'sports;winning', likes: 0 },
      { text: 'The only place success comes before work is in the dictionary.', author: 'Vidal Sassoon', tags: 'work;success', likes: 0 },
      { text: 'I’ve never lost a game I just ran out of time.', author: 'Michael Jordan', tags: 'sports;attitude', likes: 0 },
      { text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth', tags: 'sports;optimism', likes: 0 },
      { text: 'Baseball is ninety percent mental and the other half is physical.', author: 'Yogi Berra', tags: 'sports;humor', likes: 0 },
      { text: 'It ain\'t over till it\'s over.', author: 'Yogi Berra', tags: 'sports;hope', likes: 0 },
      { text: 'You can observe a lot by just watching.', author: 'Yogi Berra', tags: 'sports;observation', likes: 0 },
      { text: 'Love is the most important thing in the world, but baseball is pretty good, too.', author: 'Yogi Berra', tags: 'sports;love', likes: 0 },
      { text: 'The future ain\'t what it used to be.', author: 'Yogi Berra', tags: 'sports;future', likes: 0 },
      { text: 'I\'m not concerned with your liking or disliking me... All I ask is that you respect me as a human being.', author: 'Jackie Robinson', tags: 'sports;respect', likes: 0 },
      { text: 'A life is not important except in the impact it has on other lives.', author: 'Jackie Robinson', tags: 'sports;service', likes: 0 },
      { text: 'Above anything else, I hate to lose.', author: 'Jackie Robinson', tags: 'sports;winning', likes: 0 },
      { text: 'There are only two seasons - winter and baseball.', author: 'Bill Veeck', tags: 'sports;passion', likes: 0 },
      { text: 'During my 18 years I came to bat almost 10,000 times. I struck out about 1,700 times and walked maybe 1,800 times. You figure a ballplayer will average about 500 at bats a season. That means I played seven years without ever hitting the ball.', author: 'Mickey Mantle', tags: 'sports;statistics', likes: 0 },
      { text: 'If I knew I was going to live this long, I\'d have taken better care of myself.', author: 'Mickey Mantle', tags: 'sports;health', likes: 0 },
      { text: 'Fans don\'t boo nobodies.', author: 'Reggie Jackson', tags: 'sports;fame', likes: 0 },
      { text: 'Hitting is 50% above the shoulders.', author: 'Ted Williams', tags: 'sports;mental', likes: 0 },
      { text: 'Man is not made for defeat.', author: 'Ernest Hemingway', tags: 'persistence;resilience', likes: 0 },
      { text: 'There is no way around the hard work. Embrace it.', author: 'Roger Federer', tags: 'sports;work', likes: 0 },
      { text: 'You have to believe in the long term plan you have but you need the short term goals to motivate and inspire you.', author: 'Roger Federer', tags: 'sports;goals', likes: 0 },
      { text: 'I fear no one, but respect everyone.', author: 'Roger Federer', tags: 'sports;respect', likes: 0 },
      { text: 'Success is a journey, not a destination. The doing is often more important than the outcome.', author: 'Arthur Ashe', tags: 'sports;success', likes: 0 },
      { text: 'You are never really playing an opponent. You are playing yourself, your own highest standards, and when you reach your limits, that is real joy.', author: 'Arthur Ashe', tags: 'sports;standards', likes: 0 },
      { text: 'True heroism is remarkably sober, very undramatic. It is not the urge to surpass all others at whatever cost, but the urge to serve others at whatever cost.', author: 'Arthur Ashe', tags: 'sports;heroism', likes: 0 },
      { text: 'Clothes make the man. Naked people have little or no influence on society.', author: 'Mark Twain', tags: 'humor;society', likes: 0 },
      { text: 'Get your facts first, then you can distort them as you please.', author: 'Mark Twain', tags: 'humor;facts', likes: 0 },
      { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain', tags: 'motivation;action', likes: 0 },
      { text: 'Kindness is the language which the deaf can hear and the blind can see.', author: 'Mark Twain', tags: 'kindness;communication', likes: 0 },
      { text: 'Travel is fatal to prejudice, bigotry, and narrow-mindedness.', author: 'Mark Twain', tags: 'travel;wisdom', likes: 0 },
      { text: 'Whenever you find yourself on the side of the majority, it is time to pause and reflect.', author: 'Mark Twain', tags: 'wisdom;individuality', likes: 0 },
      { text: 'If you tell the truth, you don\'t have to remember anything.', author: 'Mark Twain', tags: 'truth;honesty', likes: 0 },
      { text: 'A lie can travel half way around the world while the truth is putting on its shoes.', author: 'Mark Twain', tags: 'truth;lies', likes: 0 },
      { text: 'Sanity and happiness are an impossible combination.', author: 'Mark Twain', tags: 'humor;happiness', likes: 0 },
      { text: 'Never argue with stupid people, they will drag you down to their level and then beat you with experience.', author: 'Mark Twain', tags: 'humor;wisdom', likes: 0 },
      { text: 'The best way to cheer yourself up is to try to cheer somebody else up.', author: 'Mark Twain', tags: 'happiness;service', likes: 0 },
      { text: 'Don\'t go around saying the world owes you a living. The world owes you nothing. It was here first.', author: 'Mark Twain', tags: 'responsibility;reality', likes: 0 },
      { text: 'Wrinkles should merely indicate where smiles have been.', author: 'Mark Twain', tags: 'age;smile', likes: 0 },
      { text: 'Books are a uniquely portable magic.', author: 'Stephen King', tags: 'books;magic', likes: 0 },
      { text: 'Hope is a good thing, maybe the best of things, and no good thing ever dies.', author: 'Stephen King', tags: 'hope;life', likes: 0 },
      { text: 'Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.', author: 'Stephen King', tags: 'fear;inner-demons', likes: 0 },
      { text: 'The scariest moment is always just before you start.', author: 'Stephen King', tags: 'fear;action', likes: 0 },
      { text: 'Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.', author: 'Stephen King', tags: 'talent;work', likes: 0 },
      { text: 'You can, you should, and if you’re brave enough to start, you will.', author: 'Stephen King', tags: 'courage;action', likes: 0 },
      { text: 'Amateurs sit and wait for inspiration, the rest of us just get up and go to work.', author: 'Stephen King', tags: 'discipline;work', likes: 0 },
      { text: 'We make up horrors to help us cope with the real ones.', author: 'Stephen King', tags: 'horror;psychology', likes: 0 },
      { text: 'French is the language that turns dirt into romance.', author: 'Stephen King', tags: 'language;humor', likes: 0 },
      { text: 'Only enemies speak the truth; friends and lovers lie endlessly, caught in the web of duty.', author: 'Stephen King', tags: 'truth;relationships', likes: 0 },
      { text: 'If you don\'t have time to read, you don\'t have the time (or the tools) to write. Simple as that.', author: 'Stephen King', tags: 'writing;reading', likes: 0 },
      { text: 'Description begins in the writer’s imagination, but should finish in the reader’s.', author: 'Stephen King', tags: 'writing;imagination', likes: 0 },
      { text: 'The road to hell is paved with adverbs.', author: 'Stephen King', tags: 'writing;humor', likes: 0 },
      { text: 'Quiet people have the loudest minds.', author: 'Stephen Hawking', tags: 'introversion;mind', likes: 0 },
      { text: 'Intelligence is the ability to adapt to change.', author: 'Stephen Hawking', tags: 'intelligence;change', likes: 0 },
      { text: 'Look up at the stars and not down at your feet.', author: 'Stephen Hawking', tags: 'perspective;inspiration', likes: 0 },
      { text: 'However difficult life may seem, there is always something you can do and succeed at.', author: 'Stephen Hawking', tags: 'hope;success', likes: 0 },
      { text: 'People who boast about their I.Q. are losers.', author: 'Stephen Hawking', tags: 'intelligence;humility', likes: 0 },
      { text: 'Life would be tragic if it weren\'t funny.', author: 'Stephen Hawking', tags: 'life;humor', likes: 0 },
      { text: 'We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.', author: 'Stephen Hawking', tags: 'science;perspective', likes: 0 }
    ];

    for (const quoteData of quotes) {
      const quote = quoteRepository.create(quoteData);
      await quoteRepository.save(quote);
    }

    console.log("Seeding complete.");
  } catch (error) {
    console.error("Error during seeding:", error);
    process.exit(1);
  } finally {
    await AppDataSource.destroy();
  }
}

seed();
